# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mint/protos/pipeline.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mint.protos import dataset_pb2 as mint_dot_protos_dot_dataset__pb2
from mint.protos import eval_pb2 as mint_dot_protos_dot_eval__pb2
from mint.protos import model_pb2 as mint_dot_protos_dot_model__pb2
from mint.protos import train_pb2 as mint_dot_protos_dot_train__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mint/protos/pipeline.proto',
  package='mint.protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1amint/protos/pipeline.proto\x12\x0bmint.protos\x1a\x19mint/protos/dataset.proto\x1a\x16mint/protos/eval.proto\x1a\x17mint/protos/model.proto\x1a\x17mint/protos/train.proto\"\x94\x02\n\x17TrainEvalPipelineConfig\x12\x37\n\x11multi_modal_model\x18\x01 \x01(\x0b\x32\x1c.mint.protos.MultiModalModel\x12.\n\x0ctrain_config\x18\x02 \x01(\x0b\x32\x18.mint.protos.TrainConfig\x12+\n\rtrain_dataset\x18\x03 \x01(\x0b\x32\x14.mint.protos.Dataset\x12,\n\x0b\x65val_config\x18\x04 \x01(\x0b\x32\x17.mint.protos.EvalConfig\x12*\n\x0c\x65val_dataset\x18\x05 \x01(\x0b\x32\x14.mint.protos.Dataset*\t\x08\xe8\x07\x10\x80\x80\x80\x80\x02'
  ,
  dependencies=[mint_dot_protos_dot_dataset__pb2.DESCRIPTOR,mint_dot_protos_dot_eval__pb2.DESCRIPTOR,mint_dot_protos_dot_model__pb2.DESCRIPTOR,mint_dot_protos_dot_train__pb2.DESCRIPTOR,])




_TRAINEVALPIPELINECONFIG = _descriptor.Descriptor(
  name='TrainEvalPipelineConfig',
  full_name='mint.protos.TrainEvalPipelineConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='multi_modal_model', full_name='mint.protos.TrainEvalPipelineConfig.multi_modal_model', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_config', full_name='mint.protos.TrainEvalPipelineConfig.train_config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='train_dataset', full_name='mint.protos.TrainEvalPipelineConfig.train_dataset', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eval_config', full_name='mint.protos.TrainEvalPipelineConfig.eval_config', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='eval_dataset', full_name='mint.protos.TrainEvalPipelineConfig.eval_dataset', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=True,
  syntax='proto2',
  extension_ranges=[(1000, 536870912), ],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=421,
)

_TRAINEVALPIPELINECONFIG.fields_by_name['multi_modal_model'].message_type = mint_dot_protos_dot_model__pb2._MULTIMODALMODEL
_TRAINEVALPIPELINECONFIG.fields_by_name['train_config'].message_type = mint_dot_protos_dot_train__pb2._TRAINCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['train_dataset'].message_type = mint_dot_protos_dot_dataset__pb2._DATASET
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_config'].message_type = mint_dot_protos_dot_eval__pb2._EVALCONFIG
_TRAINEVALPIPELINECONFIG.fields_by_name['eval_dataset'].message_type = mint_dot_protos_dot_dataset__pb2._DATASET
DESCRIPTOR.message_types_by_name['TrainEvalPipelineConfig'] = _TRAINEVALPIPELINECONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TrainEvalPipelineConfig = _reflection.GeneratedProtocolMessageType('TrainEvalPipelineConfig', (_message.Message,), {
  'DESCRIPTOR' : _TRAINEVALPIPELINECONFIG,
  '__module__' : 'mint.protos.pipeline_pb2'
  # @@protoc_insertion_point(class_scope:mint.protos.TrainEvalPipelineConfig)
  })
_sym_db.RegisterMessage(TrainEvalPipelineConfig)


# @@protoc_insertion_point(module_scope)
