# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mint/protos/preprocessor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mint/protos/preprocessor.proto',
  package='mint.protos',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1emint/protos/preprocessor.proto\x12\x0bmint.protos\"Z\n\x0cPreprocessor\x12:\n\x11\x66\x61\x63t_preprocessor\x18\x01 \x01(\x0b\x32\x1d.mint.protos.FACTPreprocessorH\x00\x42\x0e\n\x0cpreprocessor\"\x12\n\x10\x46\x41\x43TPreprocessor'
)




_PREPROCESSOR = _descriptor.Descriptor(
  name='Preprocessor',
  full_name='mint.protos.Preprocessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fact_preprocessor', full_name='mint.protos.Preprocessor.fact_preprocessor', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='preprocessor', full_name='mint.protos.Preprocessor.preprocessor',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=47,
  serialized_end=137,
)


_FACTPREPROCESSOR = _descriptor.Descriptor(
  name='FACTPreprocessor',
  full_name='mint.protos.FACTPreprocessor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=157,
)

_PREPROCESSOR.fields_by_name['fact_preprocessor'].message_type = _FACTPREPROCESSOR
_PREPROCESSOR.oneofs_by_name['preprocessor'].fields.append(
  _PREPROCESSOR.fields_by_name['fact_preprocessor'])
_PREPROCESSOR.fields_by_name['fact_preprocessor'].containing_oneof = _PREPROCESSOR.oneofs_by_name['preprocessor']
DESCRIPTOR.message_types_by_name['Preprocessor'] = _PREPROCESSOR
DESCRIPTOR.message_types_by_name['FACTPreprocessor'] = _FACTPREPROCESSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Preprocessor = _reflection.GeneratedProtocolMessageType('Preprocessor', (_message.Message,), {
  'DESCRIPTOR' : _PREPROCESSOR,
  '__module__' : 'mint.protos.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:mint.protos.Preprocessor)
  })
_sym_db.RegisterMessage(Preprocessor)

FACTPreprocessor = _reflection.GeneratedProtocolMessageType('FACTPreprocessor', (_message.Message,), {
  'DESCRIPTOR' : _FACTPREPROCESSOR,
  '__module__' : 'mint.protos.preprocessor_pb2'
  # @@protoc_insertion_point(class_scope:mint.protos.FACTPreprocessor)
  })
_sym_db.RegisterMessage(FACTPreprocessor)


# @@protoc_insertion_point(module_scope)
